### ISSUE TITLE
RemoteTech location of KSC wrong

### ISSUE THREAD

**Issue by WazWaz** [KillAshley/UL#3]
Had to edit RT Settings to fix.

**Comment by KillAshley** [comment]
Yeah RT location is hard set in it's cfg file and unable to be modified by a MM patch :(

I'm thinking about how best to deal with this situation, perhaps distributing a modified RT cfg to overwrite, or maybe i can convince the devs to allow MM patching :/

**Comment by KillAshley** [comment]
Fixed via additional cfg. More testing still needed though.

1dcdadb7850c7d3a40a7c9a118f31be8d52cbea8
